FROM ruby:2.3.3

RUN mkdir /app
WORKDIR /app

RUN bundle config git.allow_insecure true

ADD . /app/

RUN gem install bundler && bundle install --jobs 20 --retry 5

ENTRYPOINT []
# CMD ["bundle", "exec", "rspec"]
